// Distributed under the GNU Affero General Public License v3.0 or later.
// See accompanying file LICENSE or https://www.gnu.org/licenses/agpl-3.0.html for details.
import { VerticalBox, Button, HorizontalBox, LineEdit } from "std-widgets.slint";
import {Styles} from "styles.slint";
export component RendererVisualizatonsBar inherits Rectangle {
    callback toggle_edge_visualization();
    callback toggle_normal_visualization();
    in property <bool> visualize_edges;
    in property <bool> visualize_normals;
    VerticalLayout {
        height: Styles.renderer_square_button_size*2.15;
        width: Styles.renderer_square_button_size;
        alignment: space-between;
        y: (self.height) + 15px;
        x: parent.width - (self.width) - 5px;
        Rectangle {
            width: Styles.renderer_square_button_size;
            height: Styles.renderer_square_button_size;
            TouchArea {
                clicked => {toggle_edge_visualization();}
            }
            background: visualize_edges ? Styles.renderer_square_toggle_button_background_enabled : Styles.renderer_square_toggle_button_background_disabled;
            Text{text: "E";font-weight: 500;}
        }
        Rectangle {
            width: Styles.renderer_square_button_size;
            height: Styles.renderer_square_button_size;
            TouchArea {
                clicked => {toggle_normal_visualization();}
            }
            background: visualize_normals ? Styles.renderer_square_toggle_button_background_enabled : Styles.renderer_square_toggle_button_background_disabled;
            Text{text: "N";font-weight: 500;}
        }
    }
}