// Distributed under the GNU Affero General Public License v3.0 or later.
// See accompanying file LICENSE or https://www.gnu.org/licenses/agpl-3.0.html for details.
import { Slider, GroupBox, HorizontalBox, VerticalBox, GridBox, Button, ScrollView, TextEdit, LineEdit, ListView } from "std-widgets.slint";
import {Styles} from "styles.slint";
import { RendererTopBar } from "renderer_top_bar.slint";
import { RendererVisualizatonsBar } from "renderer_visualizations_bar.slint";


export component App inherits Window {
    in property <image> texture <=> image.source;
    in property <bool> visualize_edges;
    in property <bool> visualize_normals;
    out property <int> requested-texture-width: image.width / 1phx;
    out property <int> requested-texture-height: image.height / 1phx;
    // Define the callback that will be implemented in Rust
    callback click_import_obj();
    callback mouse_down_renderer(PointerEventButton);
    callback mouse_up_renderer(PointerEventButton);
    callback delete_item_by_uuid(string); //uuid
    callback undo();
    callback redo();
    callback toggle_edge_visualization();
    callback toggle_normal_visualization();

    callback mouse_scroll(length);
    callback mouse_move_renderer(length, length);

    title: "UltraMayor";
    preferred-height: 900px;
    preferred-width: 1600px;
    HorizontalBox {
        VerticalBox {
            width: 200px;
            alignment: space-between;
            HorizontalBox {
                height: 50px;
                Button {
                    text: @tr("UNDO");
                    clicked => {
                        undo();
                    }
                }

                Button {
                    text: @tr("REDO");
                    clicked => {
                        redo();
                    }
                }

                
            }
            // Button {
            //     text: @tr("IMPORT OBJ");
            //     clicked => {
            //         click_import_obj();
            //     }
            // }

        }

        VerticalBox {
            preferred-width: 700px;
            image := Image {
                height: 100%;
                TouchArea {
                    scroll-event(e) => {
                        if e.delta-y > 0 {
                            root.mouse_scroll(e.delta-y);
                            return accept;
                        } else if e.delta-y < 0 {
                            root.mouse_scroll(e.delta-y);
                            return accept;
                        }
                        return reject;
                    }
                    pointer-event(event) => {
                        if (event.kind == PointerEventKind.move) {
                            mouse_move_renderer(self.mouse_x, self.mouse_y);
                        } else if (event.kind == PointerEventKind.down) {
                            mouse_down_renderer(event.button);
                        } else if (event.kind == PointerEventKind.up) {
                            mouse_up_renderer(event.button);
                        }
                    }
                }

                RendererTopBar { }
                RendererVisualizatonsBar { 
                    visualize_edges: visualize_edges;
                    visualize_normals: visualize_normals;
                    toggle_edge_visualization() =>{toggle_edge_visualization()}
                    toggle_normal_visualization() =>{toggle_normal_visualization()}
                }
            }
        }

        // Right panel
        VerticalBox {
            width: 200px;
            VerticalLayout {
                Button {
                    text: "Action 1";
                }
                Button {
                    text: "Action 2";
                }
            }
        }
    }   
}