// Distributed under the GNU Affero General Public License v3.0 or later.
// See accompanying file LICENSE or https://www.gnu.org/licenses/agpl-3.0.html for details.
export global Styles {
    out property <float> line_edit_height_to_font_size_ratio: 2.25;
    out property <length> renderer_square_button_size: 60px;
    out property <brush> renderer_square_button_background: grey;
    out property <brush> renderer_square_toggle_button_background_enabled: green;
    out property <brush> renderer_square_toggle_button_background_disabled: red;

}